version: "26.1.1"

services:
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./FE:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./BE:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
